tasks:
  - name: Setup Android Project
    init: |
      # إنشاء المجلدات
      mkdir -p .github/workflows
      mkdir -p app/src/main/java/com/myapp/example
      mkdir -p app/src/main/res/values
      mkdir -p gradle/wrapper
      
      # إنشاء GitHub Actions workflow
      cat > .github/workflows/build-apk.yml << 'EOF'
      name: Build Android APK
      on:
        push:
          branches: [ main, master ]
        workflow_dispatch:
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v4
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temumurin'
          - name: Grant execute permission
            run: chmod +x gradlew
          - name: Build APK
            run: ./gradlew assembleDebug
          - name: Upload APK
            uses: actions/upload-artifact@v4
            with:
              name: app-debug
              path: app/build/outputs/apk/debug/*.apk
      EOF
      
      # إنشاء build.gradle الجذري
      cat > build.gradle << 'EOF'
      buildscript {
          repositories {
              google()
              mavenCentral()
          }
          dependencies {
              classpath 'com.android.tools.build:gradle:8.1.0'
          }
      }
      allprojects {
          repositories {
              google()
              mavenCentral()
          }
      }
      EOF
      
      # إنشاء settings.gradle
      cat > settings.gradle << 'EOF'
      rootProject.name = "MyApp"
      include ':app'
      EOF
      
      # إنشاء gradle.properties
      cat > gradle.properties << 'EOF'
      org.gradle.jvmargs=-Xmx2048m
      android.useAndroidX=true
      EOF
      
      # إنشاء app/build.gradle
      cat > app/build.gradle << 'EOF'
      plugins {
          id 'com.android.application'
      }
      android {
          namespace 'com.myapp.example'
          compileSdk 34
          defaultConfig {
              applicationId "com.myapp.example"
              minSdk 21
              targetSdk 34
              versionCode 1
              versionName "1.0"
          }
      }
      dependencies {
          implementation 'androidx.appcompat:appcompat:1.6.1'
      }
      EOF
      
      # إنشاء AndroidManifest.xml
      cat > app/src/main/AndroidManifest.xml << 'EOF'
      <?xml version="1.0" encoding="utf-8"?>
      <manifest xmlns:android="http://schemas.android.com/apk/res/android">
          <application
              android:label="تطبيقي"
              android:theme="@style/Theme.AppCompat.Light">
              <activity
                  android:name=".MainActivity"
                  android:exported="true">
                  <intent-filter>
                      <action android:name="android.intent.action.MAIN" />
                      <category android:name="android.intent.category.LAUNCHER" />
                  </intent-filter>
              </activity>
          </application>
      </manifest>
      EOF
      
      # إنشاء MainActivity.java
      cat > app/src/main/java/com/myapp/example/MainActivity.java << 'EOF'
      package com.myapp.example;
      import android.os.Bundle;
      import android.widget.TextView;
      import androidx.appcompat.app.AppCompatActivity;
      public class MainActivity extends AppCompatActivity {
          protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              TextView tv = new TextView(this);
              tv.setText("مرحباً! تم البناء عبر GitHub");
              tv.setTextSize(24);
              tv.setGravity(17);
              setContentView(tv);
          }
      }
      EOF
      
      # إنشاء strings.xml
      cat > app/src/main/res/values/strings.xml << 'EOF'
      <resources>
          <string name="app_name">تطبيقي</string>
      </resources>
      EOF
      
      # تحميل Gradle Wrapper
      gradle wrapper
      
      echo "✅ تم إنشاء المشروع بنجاح!"
